### PR TITLE
Fix for #41 and #68 time parsing issues, based on fixes from HamishB

### PR DESCRIPTION
**Pull request by drak7**
Fixes issues with using atof() to parse time, changed to atol() for hhmmss and atoi() for the millisecond portion. Updated parsing examples to output with proper zero padding.

### CODE REVIEW

**Comment by ladyada** [comment]
@drak7 heya matt wanna check it out?

**Comment by drak7** [comment]
It's mine :) Travis seems to be having the same issue again with sam.h.

**Comment by ladyada** [comment]
omg i need a coffee

**Comment by ladyada** [comment]
i can delete the cache - do you not have access to that in travis?

**Comment by drak7** [comment]
Oh, I guess I do! Trying that

**Comment by ladyada** [comment]
yep delete em all, this comes up when we update the SAM BSP which happens kinda often (good) but ends up confusing arduino if we have the BSP pre-cached (bad). ditto for other BSPs but they dont update as often

**Pull request merged**
