### PR TITLE
Add Actions and remove travis

### PR DESCRIPTION
**Pull request by ladyada**
@drak7 this should speed up CI by moving to actions. I've also added clang-format check so open PRs wont merge cleanly but code is prettier :)

### CODE REVIEW

**Comment by sellensr** [comment]
Should I close PR 108 and re-request?

**Comment by ladyada** [comment]
they might be ok just clang-formatting or rebasin' - i think this is worth merging sooner rather than later cause we'll only get more PRs

**Comment by sellensr** [comment]
OK, let's merge 109, then see what happens to 108. I don't think there will be a lot to clean up.

**Comment by drak7** [comment]
Nice! If we have people run clang-format on their PRs that should help keep things consistent too.

**Comment by ladyada** [comment]
thanks!

**Pull request merged**
