### PR TITLE
Redo #108 to make it merge

### PR DESCRIPTION
**Pull request by sellensr**

### CODE REVIEW

**Comment by sellensr** [comment]
would it make sense to move clang and doxygen to the front of the actions queue, as they complete much faster than the builds?

**Comment by ladyada** [comment]
hi i can split the jobs up to make faster (its already 2 x faster than travis :) but doxygen def has to be last because on pushs it updates the github pages. clang could be earlier but i think its better people get working code - then they can clang-format it (doesnt change function) and doxy (doesnt change function)

**Comment by ladyada** [comment]
@sellensr thank you for your patience, i know its not the easiest way to submit PRs - we really appreciate it :)

**Comment by sellensr** [comment]
Those pesky .DS_Store files keep creeping in. Maybe the .gitignore will keep it away. I see there is one in the Adafruit_IO library.

@ladyada I'm plugging along and learning things about tools that are new to me. Today's adventure was discovering how to install and use clang-format and run-clang-format, so I can now run the clang and doxygen checks locally before  making a PR. It may take me a while to reconcile my formatting opinions with clang ;-)

I definitely appreciate the new speedup with github actions!

**Comment by ladyada** [comment]
yay thanks!

**Comment by drak7** [comment]
No worries! You can also set up a global ignore to catch them anywhere.
Run `git config --get core.excludesfile` to see what file it is, I think it defaults to ~/.gitignore. Anything in there applies globally.

**Comment by sellensr** [comment]
Thanks -- Didn't know that. Mac doesn't come with a default, but https://gist.github.com/subfuzion/db7f57fff2fb6998a16c shows how to do the config.

**Pull request merged**
