### PR TITLE
Add some improvements to Adafruit GPS library

### PR DESCRIPTION
**Pull request by biagiom**
- Rework Adafruit_GPS class:
add public methods to get location, date, time values
update methods related to Standby mode
add public methods to manage AlwaysLocate mode (tested using Quectel L80)
update code formating (fix some whitespace errors, alignment, ...)
add some improvements to source code
- Add keywords.txt file
- Move library source code to "src" directory
- Update sketches of Adafruit_GPS library:
use new methods added to Adafruit_GPS class
fix some whitespaces errors
improve code formatting

### CODE REVIEW

**Comment by biagiom** [comment]
@ladyada, @tdicola could you please review ?
Thanks in advance and best regards.

**Comment by ladyada** [comment]
hiya, thanks for the PR, this PR has a lot of stuff going on so it may take us a while to get to it. there's also both stylisic changes (formatting, whitespace, braces) and functional changes - which makes it harder to verify as well! if you could separate the two types of changes into two PR's that would make it easier for us :)

**Comment by biagiom** [comment]
Hi @ladyada,
most of stylistic changes have been added to the second commit that updates sketches according to the changes added to the Adafruit_GPS class, but also to the first commit in some function. It's ok if I add comments to the files changed in order to distinguish stylistic changes to functional ones and to help you to review the changes ?

**Comment by ladyada** [comment]
no need to - its that they're together, not that they're uncommented, that will take longer to review!

**Comment by drak7** [comment]
We've updated a bunch so I'll close this one but feel free to rework it on top of the new code and submit a new PR.

**Pull request closed without merging**
